name: Maybe release
on:
  push:
    branches:
      - dyne
jobs:
  reflow_flavour_docker_release_build_push:
    name: Reflow flavour - Maybe tag version & release Docker image
    runs-on: ubuntu-latest
    env:
      FLAVOUR: reflow
      FLAVOUR_PATH: flavours/reflow
      DOCKER_REPO: reflow
      APP_NAME: reflow
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2 # needed for action-detect-and-tag-new-version
      -
        name: Maybe tag/release new version
        id: version
        uses: salsify/action-detect-and-tag-new-version@v2
        with:
          version-command: |
            grep -m 1 'version:' mix.exs | cut -d '"' -f2
      -
        if: steps.version.outputs.current-version == steps.version.outputs.previous-version
        name: Cancel workflow if the version has not changed
        uses: andymckay/cancel-action@0.2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: dyne
          password: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Cancel any already running releases workflows
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      -
        name: Pre-build prep
        run: mkdir forks/ && mkdir -p data/uploads/ && make rel.config.prepare && touch data/current_flavour/config/deps.path
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.release
          platforms: linux/amd64
          push: true
          tags: |
            dyne/${{ env.DOCKER_REPO }}:latest
            dyne/${{ env.DOCKER_REPO }}:${{steps.version.outputs.current-version}}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
